name: baloon_popper
description: Flutter 2D game with Flame

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.0.0
  flame_audio: ^1.0.0
  flame_forge2d: ^0.8.3
  flame_bloc: ^1.1.0
  flutter_bloc: ^8.0.1
  google_fonts: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - google_fonts/